### ISSUE TITLE
tev2-specification does not replicate on another github user account's github pages

### ISSUE THREAD

**Issue by henkvancann** [tno-terminology-design/tev2-specifications#29]
I've forked 

tev2-specification from tno-terminology-design to https://github.com/henkvancann/tev2-specifications

Because intent to work in a branch 'hvc' (my initials), I've added the new branch to the invocation list of github actions.
 
You can see here that the [Docs_deploy](https://github.com/henkvancann/tev2-specifications/actions/runs/8019370132/workflow) action script falters:
https://github.com/henkvancann/tev2-specifications/actions/runs/8019370132/job/21907096531

A run with Act (local virtual github action) gives the same results.

These are my github user setting for Pages:
![Screenshot 2024-02-23 at 14 57 30](https://github.com/tno-terminology-design/tev2-specifications/assets/479356/ca9b41da-6f38-4b95-bbe5-6b450ac0a78d)

**Comment by RieksJ** [comment]
@Ca5e pls check out the log. it seems rhat the mrgt doesnt catch this error and thus doesnt produce a good error message end dies. could that be caused by the new tools?

**Comment by Ca5e** [comment]
The MRGT is working as intended, but the error message fails to include the files that were causing the issue (I'll fix this for the next version). The terms that were copied include duplicate formPhrases, in this case `concept:tools`, caused by the `tev2-tool.md` including `tool{ss}` and `tev2-toolbox.md` including `tools` in their `formPhrases` field.

The error is caused by the updated tools, in the sense that not all previous versions checked for this issue.

![image](https://github.com/tno-terminology-design/tev2-specifications/assets/6130478/5cb6cf5d-67bd-4be8-b108-576bcd21e990)

**Comment by RieksJ** [comment]
@Ca5e tnx. when the new tool is published, can you say so in this iissue?

**Comment by Ca5e** [comment]
Version 1.1.2 of the MRGT was just published, and now reports the following.

![image](https://github.com/tno-terminology-design/tev2-specifications/assets/6130478/b4b098ae-9c98-4458-ad76-df68e2ba6064)

**Comment by RieksJ** [comment]
@Ca5e does this generate a hard error or does thetool continue as it does with other errors? which i currently think it should

**Comment by Ca5e** [comment]
> @Ca5e does this generate a hard error or does thetool continue as it does with other errors? which i currently think it should

It currently halts the output of the MRG and stops the program with an error code. This could of course be changed to only logging an error, which would mean the MRG could be output with duplicates. I believe you'd want the last option?

> @henkvancann i fixed the cause in the tev2 specs repo. copying the fix should get you going again

I believe the issue was already solved in [this](https://github.com/tno-terminology-design/tev2-specifications/commit/2e7d6d2952b9fe2694dc0f9519e75a66815d3486#diff-173b6b91dca69eae002e6fce0e745434d9754eee25abcc386687c7814057b57b) commit from a few weeks back, I think there's no match for `tools` now.

**Comment by RieksJ** [comment]
@Ca5e yes for now. its not ideal. we are increasingly looking for someone to make a start with the integrity checker tool....

**Comment by Ca5e** [comment]
I've just published MRGT v1.1.3, which only logs the error and doesn't halt the program. A rerun of the workflow should therefore run normally.

**Comment by henkvancann** [comment]
![Screenshot 2024-02-25 at 13 44 31](https://github.com/tno-terminology-design/tev2-specifications/assets/479356/7e1b6135-8674-499d-8606-1c27b70ebdee)
